### ISSUE TITLE
ws connection

### ISSUE THREAD

**Issue by shortthefomo** [bigcjat/Validator-landing-page#1]
As per these lines in the readme.

> Editing listener.py: Modify the line if necessary: uri = "ws://127.0.0.1:6009": Replace with the correct WebSocket server URI, you can find this in your validator config "port_ws_admin_local"

How do I connect this to the validators ws, if my toml is running on another box?

**Comment by shortthefomo** [comment]
Ah reading the code I think I follow what's happening the py service is running on the validator collecting the stats.... then that pushes the data to the web server host which is the php file that then consumes that data and then publishes it.

the confusing part in your readme was that your validator setup is talking about php files etc. maybe this should be split into two distinct projects. 

follow now what's happening cool beans sorry for my confusion

**Comment by bigcjat** [comment]
There are 2 folders, one with 2 python scripts you run on the validator, another with the html and the php script for your webhost.

The python script listens to your local websocket, when a key ledger is hit, it launches another python script that will gather the information on your machine and make a simple fetch to the php app script on your host and post that information. The php then authenticates your ip and api key and modifies your toml 

It is a 1 way connection

**Comment by bigcjat** [comment]
> Ah reading the code I think I follow what's happening the py service is running on the validator collecting the stats.... then that pushes the data to the web server host which is the php file that then consumes that data and then publishes it.
> 
> the confusing part in your readme was that your validator setup is talking about php files etc. maybe this should be split into two distinct projects.
> 
> follow now what's happening cool beans sorry for my confusion

The python has no purpose without the php api, 2 seperate projects would make no sense
